apiVersion: v1
kind: Service
metadata:
  name: authentication-api
  labels:
    name: authentication-api
    component: service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    name: authentication-api
    component: api
